GET http://localhost:2799/


### Crete new sale
@employeeId = E-06
@revenue = 1000
@cost = 500
@profit = 500
POST http://localhost:2799/employees/{{employeeId}}/sales
Content-Type: application/json
Accept: application/json

{
    "revenue": {{revenue}},
    "cost": {{cost}},
    "profit": {{profit}}
}

### Get sales
GET http://localhost:2799/sales


### Get sales by Id
@id = d7531bee-8f45-4857-ac0b-cb5349e18243
@get-EmployeeId = E-01
GET http://localhost:2799/employees/{{get-EmployeeId}}/sales/{{id}}

### Update sales

PUT http://localhost:2799/employees/{{get-EmployeeId}}/sales/{{id}}

{
    "revenue": 700000,
    "cost": {{cost}},
    "profit": {{profit}}
}

### Delete sales
DELETE http://localhost:2799/employees/{{get-EmployeeId}}/sales/{{id}}

### Export to excel
GET http://localhost:2799/sales/export?limit=2